apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-opentaproject-org-certificate
  namespace: ingress-nginx
spec:
  secretName: default-opentaproject-org-tls
  issuerRef:
    # The issuer created previously
    name: letsencrypt
  commonName: default.opentaproject.org
  dnsNames:
    - default.opentaproject.org
    #- opentaproject.org

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opentaproject-org-certificate
  namespace: opentaproject-org
spec:
  secretName: opentaproject-org-certificate-tls
  issuerRef:
    # The issuer created previously
    name: letsencrypt
    kind: Issuer
  commonName: opentaproject.org
  dnsNames:
    - opentaproject.org
    - "*.opentaproject.org"
