# Generated by Django 2.0.4 on 2020-07-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0011_regradetask_resultsfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='regradetask',
            name='pklfile',
            field=models.CharField(default='', max_length=255),
        ),
    ]
