# Generated by Django 3.1.5 on 2021-02-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0014_auto_20210222_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetask',
            name='subdomain',
            field=models.CharField(default='v304', max_length=255),
            preserve_default=False,
        ),
    ]
