# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2021-02-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opentasites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opentasite',
            name='db_name',
            field=models.CharField(default=models.CharField(max_length=4096, unique=True), max_length=4096, unique=True),
        ),
    ]
