# Generated by Django 3.1.5 on 2021-02-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opentasites', '0003_auto_20210205_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentasite',
            name='db_label',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opentasite',
            name='subdomain',
            field=models.CharField(default='subdomain', max_length=4096),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opentasite',
            name='db_name',
            field=models.CharField(max_length=4096),
        ),
    ]
