# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2022-07-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opentasites', '0004_auto_20210223_2354'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='opentasite',
            constraint=models.UniqueConstraint(fields=('db_name',), name='Database must be unique'),
        ),
        migrations.AddConstraint(
            model_name='opentasite',
            constraint=models.UniqueConstraint(fields=('subdomain',), name='Subdomain value must be unique'),
        ),
    ]
