# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2022-07-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opentasites', '0005_auto_20220721_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentasite',
            name='creator',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='opentasite',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='opentasite',
            name='db_label',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
