# Generated by Django 3.1.5 on 2022-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opentasites', '0006_auto_20220721_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentasite',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
