# Generated by Django 3.1.5 on 2022-09-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opentasites', '0007_opentasite_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opentasite',
            name='Database must be unique',
        ),
        migrations.RemoveConstraint(
            model_name='opentasite',
            name='Subdomain value must be unique',
        ),
        migrations.AddField(
            model_name='opentasite',
            name='course_key',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterUniqueTogether(
            name='opentasite',
            unique_together={('subdomain', 'course_key')},
        ),
    ]
