#!/bin/bash
BASE_VERSION='v1500'
cat Dockerfile.template  | sed "s/VERSION/${BASE_VERSION}/" > Dockerfile
echo Make sure dockerfile has ${BASE_VERSION} for base image
export githash=`git rev-parse --short HEAD`
docker build --tag opentaproject/openta-frontend:${VERSION} .
docker push opentaproject/openta-frontend:${VERSION}
docker tag opentaproject/openta-frontend:${VERSION} opentaproject/openta-frontend:${githash}
docker push opentaproject/openta-frontend:${VERSION}
