[program:alpha-plus-clean_rq_worker]
command=/srv/alpha-plus-clean/django/env/bin/python manage.py rqworker
directory=/srv/alpha-plus-clean/django/backend
user=www-data
autostart=true
autorestart=true
