apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opentaproject-com-certificate
  namespace: opentaproject-com
spec:
  secretName: opentaproject-com-tls
  issuerRef:
    # The issuer created previously
    name: letsencrypt
    kind: Issuer
  commonName: opentaproject.com
  dnsNames:
    - opentaproject.com
    - "*.opentaproject.com"
