#!/bin/bash
python manage.py migrate --database=$1
python manage.py loaddata fixtures/auth.json --database=$1
python manage.py loaddata fixtures/course.json --database=$1
python manage.py createcachetable --database=$1
