#!/bin/bash
export DISPLAY=''
#if [ -z ${VIRTUAL_ENV+x} ]; then
#  echo "You probably want to be in the corresponding python virtual env when running the tests.";
#  else
python manage.py test -v 2 --settings=backend.settings_test $*;
#    fi
