#!/bin/bash
# crontab entry
#
# * * * * * /srv/openta/django/backend/db_autoreload 
#
if test  -f /usr/local/bin/supervisord  ; then
	bindir=/usr/local/bin
else
	bindir=/srv/openta/django/env/bin
fi
export PATH="/srv/openta/django/env/bin:/srv/openta/django/backend:$PATH"
cd /srv/openta/django/backend
date >> /tmp/autocheck
pidfile=/tmp/supervisord.pid
supervisorpid=`cat $pidfile`
#pidage=`ps -o etimes= -p ${supervisorpid}`
pidage=$(($(date +%s) - $(date +%s -r $pidfile)))
#echo domainage=$domainage pidage=${pidage}
#echo sdiff=$sdiff
#echo diff=$diff
if test -d /tmp/outdated ; then
    domains=`ls /tmp/outdated`
    for domain in $domains 
    do
    	#echo domain=$domain
    	domainage=$(($(date +%s) - $(date +%s -r /tmp/outdated/$domain)))
    	#echo domain=$domain domainage=$domainage pidage=$pidage
    	diff=`echo "${domainage} - ${pidage}" | bc`
    	if [ $diff \< 0 ] ;
    	then
    		echo " ${domain} Needs renewal $diff"
    		db_reset $domain
    		touch /tmp/outdated/$domain
    	#else 
    	#	echo "${domain} up to date $diff"
    	fi;
    done
fi
last_reset_file="/subdomain-data/last_reset"
if test -f "${last_reset_file}" ; then
	resetage=$(($(date +%s) - $(date +%s -r ${last_reset_file})))
	diff=`echo "${resetage} - ${pidage}" | bc`
	if [ $diff \< 0 ] ;
	then
		echo "supervisorctl needs restart"
		$bindir/supervisorctl reload
	#else 
	#	echo "no restart needed"
	fi;
fi;

