#!/usr/bin/env bash 
pg_dump=`which pg_dump`
export SUBDOMAIN=$1
subdomain=$1
dirname="/subdomain-data/${subdomain}"
if test -f  /usr/local/opt/postgresql/bin/pg_dump 
then
	pg_dump=/usr/local/opt/postgresql/bin/pg_dump
elif  test -f  /usr/bin/pg_dump  
then
	pg_dump=/usr/bin/pg_dump
fi 

if test -e $dirname ; then
	echo "COURSE ${subdomain} ALREADY EXISTS "
	exit
fi
if [ -z "$2" ] ; then
	echo "No email supplied"
	exit
fi
./db_init $1
./db_migrate $1
email=$2
dbnamefile="/subdomain-data/${subdomain}/dbname.txt"
echo $dbnamefile


if test -e $dbnamefile ; then
	echo "FILE FOUND"
	dbname=`cat $dbnamefile | tr -d '\n'`
else
	echo $dbnamefile not found so exit;
	exit
fi
echo "NOW FIX SUPERUSER ${subdomain} ${email}"
mkdir -p "/subdomain-data/${subdomain}/backups"
mkdir -p "/subdomain-data/${subdomain}/media"
chmod 0755 "/subdomain-data/${subdomain}/media"
./db_loaddata $1
./db_repair ${subdomain}
./db_migrate ${subdomain}
./db_fix_superuser ${subdomain} ${email}
$pg_dump -Fc $dbname > /subdomain-data/${subdomain}/${dbname}.db
