#!/bin/bash
# shellscript to migrate all


if [ "$#" == "0" ]; then
	echo "USAGE ${0} --dry-run [true|false]"
	exit 1
fi

dryrun='true'

for i in "$@" ;
do
    case $1 in

	'--user')
		shift 1;
		#echo user $1
		user=$1
		;;
	
	'--dry-run')
		shift 1;
		#echo dryrun $1
		dryrun=$1
		;;
     esac
     shift 1;
done

#echo DRYRUN IS ${dryrun}

if [ "${dryrun}" == 'true' ]; then
	#echo "ÐRYRUN IS TRUE"
	doit=false;
elif [ "${dryrun}" == 'false' ] ; then
	#echo "DRYRUN IS FALSE"
	doit=true;
else
	#echo "DRYRUN NOT STRING"
	doit=false;
fi
if [ "${dryrun}" == '' ]; then
	echo "USAGE = ${0} --dry-run [true|false]"
fi

subs=`ls /subdomain-data/*/dbname.txt | awk '{split($0,a,"/"); print a[3] }'` 
if ${doit} ; then
	python manage.py migrate --database=default
	python manage.py migrate --database=sites
fi
for subdomain in $subs; do
	if ${doit} ; then
		#echo "SUBDOMAIN=$subdomain python manage.py migrate --settings=backend.settings_manage --database=${subdomain}"
		if SUBDOMAIN=$subdomain python manage.py migrate --check --settings=backend.settings_manage --database=${subdomain} > /dev/null 2>&1 ; then
			echo "${subdomain} ok"
		else 
			echo "${subdomain} not ok"
			SUBDOMAIN=$subdomain python manage.py migrate  --settings=backend.settings_manage --database=${subdomain} > /dev/null 2>&1 
		fi
	else :
		echo would migrate $subdomain
	fi
	
done
