#!/usr/bin/env bash
if [ -e /tmp/env ] ; then 
	source /tmp/env
fi
cd /srv/openta/django/backend;
if [ -n $DBHOST ] ; then
	export PGHOST=${DBHOST}
fi
for i in /subdomain-data/$1
do
        subdomain=`basename $i`
        echo $subdomain
        dbnamefile="/subdomain-data/${subdomain}/dbname.txt"
        echo $dbnamefile
        if test -e $dbnamefile ; then
                echo "FILE FOUND"
                dbname=`cat $dbnamefile | xargs`
        else
                echo "FILINITIALIZED"
                break
        fi
        echo $subdomain $dbname
        dbfile=${i}/${dbname}.db
        if test -f ${dbfile} ; then
                echo DBFILE = $dbfile
                echo DBNAME = $dbname
                #psql -U postgres -c "DROP DATABASE IF EXISTS $dbname;"
		psql -U postgres -d $dbname  -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
		#sleep 10
                #psql -U postgres -c "CREATE DATABASE $dbname OWNER postgres;"
                echo Create datbase $dbname from $dbfile
                cat $dbfile | pg_restore -U postgres --no-owner -d $dbname
        else
                echo Cannot restore: $dbfile does not exist
        fi
        SUBDOMAIN=$subdomain /usr/bin/env python manage.py migrate --settings=backend.settings_manage  --database=$subdomain
done





