#!/bin/bash
d=`find /subdomain-data -mindepth 1 -maxdepth 1 -type d -mtime -30`
echo D=$d
if [[ -n "$RSYNC_DEST"  ]] ; then 
	dest=${RSYNC_DEST}
	for i in $d;
	do
		echo do $i
		if [ -f $i/dbname.txt ] ; then 
			rsync -av -e "$SSH_CMD" $i  $dest
		else
			echo $i is not an exercisedir
		fi

	done
else 
	echo RSYNC_DEST IS NOT DEFINED
fi
