#!/usr/bin/env bash
for i in /subdomain-data/$1
do
        subdomain=`basename $i`
        echo $subdomain
        dbnamefile="/subdomain-data/${subdomain}/dbname.txt"
        echo $dbnamefile
        if test -e $dbnamefile ; then
                echo "FILE FOUND"
                old_dbname=`cat $dbnamefile | xargs`
        else
                echo "FILINITIALIZED"
                break
        fi
        old_dbfile=${i}/${old_dbname}.db
	rm ${i}/$subdomain
        tmp_dbname=`head /dev/urandom | LC_ALL=C tr -dc a-z | head -c 8`
        echo TMP_DBNAME = $tmp_dbname
        echo OLD_DATABASE = $old_dbname
        if test -f ${old_dbfile} ; then
                psql -U postgres -c "DROP DATABASE IF EXISTS $tmp_dbname;"
                echo Create temporary datbase $tmp_dbname 
                psql -U postgres -c "CREATE DATABASE $tmp_dbname OWNER postgres;"
		psql -U postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '"${old_dbname}"' AND pid <> pg_backend_pid();"
		psql -U postgres -c "DROP DATABASE IF EXISTS $old_dbname;"
                cat $old_dbfile | pg_restore -U postgres --no-owner -d $tmp_dbname
		psql -U postgres -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '"${tmp_dbname}"' AND pid <> pg_backend_pid();"
                psql -U postgres -c "ALTER DATABASE $tmp_dbname   RENAME TO $old_dbname;"
		sleep 3
		psql -U postgres -c " GRANT CONNECT ON DATABASE $old_dbname TO PUBLIC,postgres;"

        else
                echo Cannot restore: $dbfile does not exist
        fi
        SUBDOMAIN=$subdomain python manage.py migrate --settings=backend.settings_manage  --database=$subdomain
        SUBDOMAIN=$subdomain python manage.py  repair_subdomain --settings=backend.settings_manage
done
touch /subdomain-data/last_reset

