#!/bin/bash
#subdomains='fim770-tif155-2024'
subdomains='ffy144-2024 tif400-2024'
# ./db_regrade   fim770-tif155-2024  > fim770-tif155-2024.out
# ./db_regrade   ffm516-2024  > ffm516-2023.out
# ./db_regrade   tif375-2024  > tif375-2024.out
# ./db_regrade   nn-2023   > nn-2023.out
# ./db_regrade   tms137-2023   > tms137-2023.out
# ./db_regrade   ffy144-2024 > ffy144-2024.out
for  subdomain in $subdomains 
do :
	export SUBDOMAIN=$subdomain
	echo DO $subdomain
	rm -rf /tmp/$subdomain
	mkdir -p /tmp/$subdomain/regrade
	chmod a+w /tmp/$subdomain/regrade
	python manage.py recalculate --accept=False --subdomain=$subdomain &>  ${subdomain}.out
done
