#!/bin/bash
export CLOUDSDK_PYTHON='/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9'
export githash=`git rev-parse --short HEAD`
gsutil -m -o GSUtil:parallel_process_count=1 -o GSUtil:parallel_thread_count=24 cp -r deploystatic gs://opentaproject-cdn-bucket/${VERSION}/
gsutil -m -o GSUtil:parallel_process_count=1 -o GSUtil:parallel_thread_count=24 cp -r static/icons gs://opentaproject-cdn-bucket/
mkdir -p ./${VERSION}-deploystatic
cp -rp deploystatic/* ./${VERSION}-deploystatic
#gsutil -m -o GSUtil:parallel_process_count=1 -o GSUtil:parallel_thread_count=24 cp -r deploystatic gs://opentaproject-cdn-bucket/latest/
echo DONE COPYING ${VERSION}
