#!/bin/bash
#export PGUSER='postgres'
#export PGHOST='db-server'
hash=`date "+%Y-%m-%d-%H:%M:%S"`
echo "backup ${hash}"
if [[ "$*" == *"--force"* ]]
then
    force=true
else
    force=false
fi
for i in /subdomain-data/$1
do
	subdomain=`basename $i`
	dbnamefile="/subdomain-data/${subdomain}/dbname.txt"
	touchfile="/subdomain-data/${subdomain}/touchfile"
	echo "do db_backup ${subdomain}"
	if test -e $touchfile || ${force}; then
		echo "touchfile ${touchfile} exists"
    		if test -e $dbnamefile ; then
			mkdir -p "/subdomain-data/${subdomain}/backups"
			SUBDOMAIN=$subdomain python manage.py migrate --settings=backend.settings_manage --database=${subdomain}
    			dbname=`cat $dbnamefile | tr -d '\n'`
			#pg_dump -C -Fc $dbname > /subdomain-data/${subdomain}/${dbname}.db
			#/usr/bin/pg_dump -Fc $dbname > /subdomain-data/${subdomain}/${dbname}.db
			echo /usr/local/opt/postgresql/bin/pg_dump  -Fc $dbname > /subdomain-data/${subdomain}/${dbname}.db
			/usr/local/opt/postgresql/bin/pg_dump  -Fc $dbname > /subdomain-data/${subdomain}/${dbname}.db
			echo cp /subdomain-data/${subdomain}/${dbname}.db  /subdomain-data/${subdomain}/backups/${dbname}-${hash}.db
			cp /subdomain-data/${subdomain}/${dbname}.db  /subdomain-data/${subdomain}/backups/${dbname}-${hash}.db
			dat=`date`
			echo "${dat} subdomain ${subdomain} with datatabse ${dbname} was backed up to  ${dbname}-${hash}.db "
		fi
		rm -f ${touchfile}
		dir=/subdomain-data/${subdomain}/backups
		latest=`ls -rt ${dir}/*-V*.db 2> /dev/null | tail -n 1`
		echo latest=${latest}
		if [[ ${latest}  == '' ]] ; then
		        echo 'V file not found'
			num='0'
		else
		        echo 'V file found'
			latest=`basename ${latest}`
			num=`echo ${latest} | sed 's/[a-zA-Z\.]//g' | sed 's/-//'`
			num="$(( ( $num + 1 )%7  ))"
		fi
		cp ${dir}/../${dbname}.db ${dir}/${dbname}-V${num}.db
		echo $num

	fi


done
