#!/bin/bash
SSLMODE=disable
export SUBDOMAIN=$1
for i in /subdomain-data/$1
do
    ./osx_db_backup $1
    subdomain=`basename $i`
    dbnamefile="/subdomain-data/${subdomain}/dbname.txt"
    echo $dbnamefile
    if test -e $dbnamefile ; then
    	echo "FILE FOUND"
    	dbname=`cat $dbnamefile | xargs`
    	echo DATABASE is  $dbname
    	cmd="SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname='"${dbname}"';"
    	echo $cmd
    	psql  -U postgres -c "$cmd"
    	psql  -U postgres -c "DROP DATABASE IF EXISTS ${dbname};"
    	sleep 3
    	randname=`head /dev/urandom | LC_ALL=C tr -dc a-z | head -c 8`
    else
	echo "$dbnamefile does not exist"
	exit
    fi
    mv /subdomain-data/${subdomain} /subdomain-data/deleted/${subdomain}-$randname
done
