#!/bin/bash
for i in /subdomain-data/$1
do
	subdomain=`basename $i`
	echo $subdomain
	dbnamefile="/subdomain-data/${subdomain}/dbname.txt"
	echo $dbnamefile
    	if test -e $dbnamefile ; then
    		echo "FILE FOUND"
    		dbname=`cat $dbnamefile | xargs`
        else
    		echo "FILINITIALIZED"
		break
	fi
	echo $subdomain $dbname
	dbfile=${i}/${dbname}.db
	if test -f ${dbfile} ; then
		echo DBFILE = $dbfile
		echo DBNAME = $dbname
		/usr/local/opt/postgresql/bin/psql -U postgres -c "DROP DATABASE IF EXISTS $dbname;"
		/usr/local/opt/postgresql/bin/psql -U postgres -c "CREATE DATABASE $dbname OWNER postgres;"
		echo Create datbase $dbname from $dbfile
		cat $dbfile | pg_restore -U postgres --no-owner -d $dbname
	else
		echo Cannot restore: $dbfile does not exist
	fi
	SUBDOMAIN=$subdomain python manage.py migrate --settings=backend.settings_manage  --database=$subdomain
	#SUBDOMAIN=$subdomain python manage.py  repair_subdomain --settings=backend.settings_manage
	#SUBDOMAIN=$subdomain python manage.py calculate_results
	#SUBDOMAIN=$subdomain python manage.py reinitialize
	#SUBDOMAIN=$subdomain python manage.py calculate_results
done
# db_init fim770
# db_migrate fim770
# db_loaddata fim770
# db_init fim770
# db_restore fim770
# db_migrate fim770


#https://dba.stackexchange.com/questions/90258/pg-restore-archiver-db-could-not-execute-query-error-schema-public-alre


#mbp:ffm521 ostlund$ psql -U postgres
#psql (13.2)
#Type "help" for help.
#
#postgres=# DROP DATABASE openta_2018
#postgres-# ;
#DROP DATABASE
#postgres=# create DATABASE openta_2018;
#CREATE DATABASE
#postgres=# /c openta_2018;
#ERROR:  syntax error at or near "/"
#LINE 1: /c openta_2018;
#        ^
#postgres=# \c openta_2018;
#You are now connected to database "openta_2018" as user "postgres".
#openta_2018=# DROP SCHEMA IF EXISTS public;
#DROP SCHEMA
#openta_2018=# CREATE SCHEMA public;
#CREATE SCHEMA
#openta_2018=#
#\q
#DROP DATABASE openta_2018
#CREATE DATABASE openta_2018 OWNER openta;
#DROP SCHEMA public;
#cat /subdomain-data/ffm521old/openta_2018.db | pg_restore  -U postgres  --no-owner -d openta_2018
###ALTER DATABASE name OWNER TO new_owner;
#621  ls
#  622  ./db_init ffm521old
#  623  ./db_migrate ffm521old
#  624  ./db_loaddata ffm521old
#  625  ./db_restore ffm521old
#  626  pyrun
#  627  history
#  628  ./db_init ffm521old
#  629  ./db_restore ffm521old
#  630  ./db_migrate ffm521old
#  631  pyrun
#  632  history

#postgres=# \c fdmewxor;
#You are now connected to database "fdmewxor" as user "postgres".
#fdmewxor=# ALTER TABLE course_course
#fdmewxor-# DROP COLUMN use_lti;
#ALTER TABLE
