#!/bin/bash
export SUBDOMAIN=$1
subdomain=$1
dirname="/subdomain-data/${subdomain}"
if test -e $dirname ; then
	echo "COURSE ${subdomain} ALREADY EXISTS "
	exit
fi
if [ -z "$2" ] ; then
	echo "No email supplied"
	exit
fi
./db_init $1
./db_migrate $1
./db_loaddata $1
email=$2
dbnamefile="/subdomain-data/${subdomain}/dbname.txt"
echo $dbnamefile


if test -e $dbnamefile ; then
	echo "FILE FOUND"
	dbname=`cat $dbnamefile | tr -d '\n'`
else
	echo $dbnamefile not found so exit;
	exit
fi
echo "CREATECOURSE" ${subdomain}
SUBDOMAIN=$subdomain python manage.py fix_superuser  --email=${email} --subdomain=${subdomain}
mkdir -p "/subdomain-data/${subdomain}/backups"
/usr/local/opt/postgresql/bin/pg_dump -Fc $dbname > /subdomain-data/${subdomain}/${dbname}.db
