apiVersion: v1
kind: Service
metadata:
  name: tailwind
spec:
  type: ClusterIP
  selector:
    app: tailwind
  ports:
    - port: 80
      targetPort: 8080 # HITS nginx
      name: http
    - port: 3200
      targetPort: 3200 # HITS nginx
      name: http3200
