# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-11-16 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0079_aggregation_image_exists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0025_auto_20191027_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tried_all', models.BooleanField(default=False)),
                ('user_is_correct', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('image_exists', models.BooleanField(default=False)),
                ('image_date', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('audit_needs_attention', models.BooleanField(default=False)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_from_answers', to='course.Course')),
                ('exercise', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_from_answers', to='exercises.Exercise')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_from_exercises', to='course.Course')),
                ('exercise', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_from_exercises', to='exercises.Exercise')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('course', 'user', 'exercise')},
        ),
    ]
