# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-11-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0002_answers_ready_for_audit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='ready_for_audit',
            new_name='all_complete',
        ),
    ]
