# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-11-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0003_auto_20191118_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='date',
            new_name='date_complete',
        ),
    ]
