# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-11-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0004_auto_20191120_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
