# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-11-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0005_answers_answer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='complete_by_deadline',
            field=models.BooleanField(default=False),
        ),
    ]
