# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-11-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0007_auto_20191122_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='questionlist_is_empty',
            field=models.BooleanField(default=False),
        ),
    ]
