# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-01-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0009_answers_audit_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='force_passed',
            field=models.BooleanField(default=False),
        ),
    ]
