# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-01-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0010_answers_force_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
    ]
