# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-01-16 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0025_auto_20191027_2130'),
        ('exercises', '0080_auto_20191118_2113'),
        ('aggregation', '0012_answers_force_failed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Aggregation',
        ),
    ]
