# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-06-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0013_auto_20200116_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregation',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
