# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0014_aggregation_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregation',
            name='points',
            field=models.TextField(blank=True, default=''),
        ),
    ]
