#!/usr/bin/env bash
subdomain=$1
coursedir=/subdomain-data/${subdomain}
echo COURSEDIR = ${coursedir}
mkdir -p ${coursedir}
echo $subdomain
dbnamefile=${coursedir}/dbname.txt
if test -f ${dbnamefile}; then
	dbname=`cat ${dbnamefile}`
else 
	dbname=`head /dev/urandom | LC_ALL=C tr -dc a-z | head -c 8`
	echo $dbname > $coursedir/dbname.txt
fi
psql -U postgres -c "CREATE DATABASE $dbname OWNER ${PGUSER};"
./db_migrate ${subdomain}
for fix in auth.json   mini.json; # course.json  auth.json ; # superuser.json ; # auth.json users.json course.json permissions.json 
do
	echo DO ${fix}
	rm /tmp/all.json;
	sed s/SUBDOMAIN/${subdomain}/ < fixtures/${fix} > /tmp/all.json;
	SUBDOMAIN=${subdomain} python manage.py  loaddata  -i /tmp/all.json --settings=backend.settings_manage --database=${subdomain}
done
./db_migrate $subdomain
cmd="BEGIN ; UPDATE course_course SET opentasite = '$subdomain' ; COMMIT ;  "
psql -U postgres -d $dbname -c "$cmd"
cmd="BEGIN ; UPDATE course_course SET course_name = 'course-$subdomain' ; COMMIT ;  "
psql -U postgres -d $dbname -c "$cmd"
cmd="BEGIN ; UPDATE course_course SET data = '\"{}\"' ; COMMIT ;  "
psql -U postgres -d $dbname -c "$cmd"
mkdir -p "/subdomain-data/${subdomain}/backups"
mkdir -p "/subdomain-data/${subdomain}/media"
chmod 0755 "/subdomain-data/${subdomain}/media"

