#!/bin/bash
SSLMODE=disable
export SUBDOMAIN=$1
for i in /subdomain-data/$1
do
    subdomain=`basename $i`
    dbnamefile="/subdomain-data/${subdomain}/dbname.txt"
    echo $dbnamefile
    if ! test -e /subdomain-data/${subdomain} ;  then
	mkdir -p /subdomain-data/${subdomain}
    fi
    if test -e $dbnamefile ; then
    	echo "FILE FOUND"
    	dbname=`cat $dbnamefile | tr -d '\n'`
    else
	randname=`head /dev/urandom | LC_ALL=C tr -dc a-z | head -c 8`
    	echo "FILINITIALIZED"
    	dbname=${randname}
    fi
    echo $dbname
    mkdir -p /subdomain-data/${subdomain}    # THIS SETS UP SETTINGS.PY TO MAKE A CONNECTION TO THE  DATABASE
    echo $dbname > $dbnamefile
    touch /subdomain-data/${subdomain}/subdomain-${subdomain}
    psql  -U postgres -c "DROP DATABASE ${dbname};"
    psql  -U postgres -c "CREATE DATABASE ${dbname} OWNER postgres;"
done
