#!/usr/bin/env bash
if [  "$PGHOST" = "pgbouncer-service" ] ; then
        export PGHOST=db-server
fi
zipfile=$1
subdomain=$2
tmpdir="/tmp/zip"
rm -rf $tmpdir ;
mkdir -p $tmpdir;
unzip  -o -q $zipfile -d $tmpdir
for i in html xsl csv index.html README
do
	rm -rf $tmpdir/$i
done
dbnamefile=$tmpdir/dbname.txt
dbname=`cat $dbnamefile`
new_dbname=`head /dev/urandom | LC_ALL=C tr -dc a-z | head -c 8`
echo $new_dbname > $tmpdir/dbname.txt
if [ ! -f $tmpdir/${dbname}.db ] ; then
	echo "ERROR: NO IMPORT DONE; NO DATABASE IN ZIP!" >&2 
	exit
fi
mv $tmpdir/${dbname}.db $tmpdir/${new_dbname}.db
oldsubdomain=`basename $tmpdir/subdomain-* | sed "s/subdomain-//"`
rm $tmpdir/subdomain-*
touch $tmpdir/subdomain-$subdomain
echo $subdomain
dbname=$new_dbname
dbnamefile=$tmpdir/$dbname.txt
if [ -d /subdomain-data/$subdomain ] ; then
	echo $subdomain exists
	mv /subdomain-data/$subdomain /subdomain-data/deleted/$subdomain-$new_dbname
fi 
echo $subdomain does not exist
mv $tmpdir/ /subdomain-data/$subdomain/
psql -U postgres -c "CREATE DATABASE $dbname OWNER postgres;"
cat /subdomain-data/$subdomain/$dbname.db | pg_restore -U postgres --no-owner -d $dbname;
echo DB = $dbname
sleep 1
cmd="BEGIN ; UPDATE course_course SET opentasite = '$subdomain' ; COMMIT ;  "
psql -U postgres -d $dbname -c "$cmd"
cmd="BEGIN ; UPDATE course_course SET course_name = 'course-$subdomain' ; COMMIT ;  "
psql -U postgres -d $dbname -c "$cmd"
cmd="BEGIN ; UPDATE course_course SET data = '\"{}\"' ; COMMIT ;  "
psql -U postgres -d $dbname -c "$cmd"
cmd="BEGIN ;  UPDATE exercises_imageanswer SET image = REPLACE(image,'$oldsubdomain','$subdomain') ; COMMIT ; "
psql -U postgres -d $dbname -c "$cmd"
cmd="BEGIN ;  UPDATE exercises_imageanswer SET pdf = REPLACE(pdf,'$oldsubdomain','$subdomain') ; COMMIT ; "
psql -U postgres -d $dbname -c "$cmd"

