# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(default='Created', max_length=255)),
            ],
        ),
    ]
