# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import workqueue.models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuetask',
            old_name='result',
            new_name='status',
        ),
        migrations.AddField(
            model_name='queuetask',
            name='result_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=workqueue.models.result_file_name),
        ),
        migrations.AddField(
            model_name='queuetask',
            name='result_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
