# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0002_auto_20170619_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetask',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
