# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0004_queuetask_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuetask',
            name='result_text',
        ),
        migrations.AddField(
            model_name='queuetask',
            name='rq_id',
            field=models.CharField(default='__no_id__', max_length=255),
        ),
    ]
