# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0005_auto_20170627_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuetask',
            name='rq_id',
        ),
    ]
