# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-05-16 11:29

from django.db import migrations, models
import workqueue.models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0006_remove_queuetask_rq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetask',
            name='result_file',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, upload_to=workqueue.models.result_file_name),
        ),
    ]
