# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-07-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0084_exercisemeta_locked'),
        ('workqueue', '0007_auto_20190516_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegradeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='exercises.Exercise')),
            ],
        ),
    ]
