# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-07-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0008_regradetask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regradetask',
            name='exercise',
        ),
        migrations.DeleteModel(
            name='RegradeTask',
        ),
    ]
