# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-07-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0010_regradetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='regradetask',
            name='resultsfile',
            field=models.CharField(default='', max_length=255),
        ),
    ]
