# Generated by Django 2.0.4 on 2020-07-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0012_regradetask_pklfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='regradetask',
            name='status',
            field=models.CharField(default='', max_length=64),
        ),
    ]
