# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2021-02-22 18:56

import django.core.files.storage
from django.db import migrations, models
import workqueue.models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0013_regradetask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetask',
            name='result_file',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/subdomain-data'), upload_to=workqueue.models.result_file_name),
        ),
    ]
