# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2021-02-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0016_auto_20210224_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='regradetask',
            name='subdomain',
            field=models.CharField(default='', max_length=255),
        ),
    ]
