# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 4.1.7 on 2025-03-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0017_regradetask_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAnalyzeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0)),
                ('exercise_key', models.CharField(default='', max_length=255)),
                ('subdomain', models.CharField(default='', max_length=255)),
                ('resultsfile', models.CharField(default='', max_length=255)),
                ('pklfile', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
