# Generated by Django 4.1.7 on 2025-03-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0018_answeranalyzetask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerAnalyzeTask',
            new_name='AnalyzeTask',
        ),
    ]
