apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
  namespace: cert-manager
spec:
  secretName: acme-dns3
  issuerRef:
    name: letsencrypt-staging
  commonName: opentaproject.com
  dnsNames:
  - opentaproject.com
  #- "*.opentaproject.com"
