FROM python:3.5
MAINTAINER Hampus Linander

# Recommended method for installing nodejs with package manager on Debian (minus sudo)
RUN (curl -sL https://deb.nodesource.com/setup_8.x | bash -)\
    && apt-get update \
    && apt-get install -y \
    nodejs \
    npm

RUN npm i npm@latest -g
RUN npm install -g brunch

RUN apt-get update && apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

EXPOSE 9485-9495

