FROM python:3.5
MAINTAINER Hampus Linander

# Recommended method for installing nodejs with package manager on Debian (minus sudo)
RUN (curl -sL https://deb.nodesource.com/setup_8.x | bash -)\
    && apt-get update \
    && apt-get install -y \
    nodejs \
    npm

RUN npm i npm@latest -g
RUN npm install -g brunch

COPY package.json /tmp/openta/frontend/package.json

WORKDIR /tmp/openta/frontend
RUN npm -g install

EXPOSE 9485-9495

