#!/bin/bash

if [[ $# -eq 0 ]] ; then
	echo 'Usage: ./createhttpsissuer EMAIL'
	exit 0
fi

export EMAIL=$1
TEMPLATE_DIR=template
envsubst '$EMAIL' < $TEMPLATE_DIR/letsencrypt-issuer.yaml.template > letsencrypt-issuer.yaml
