apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: regional-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: regionalpd-storageclass
