FROM python:3.6

## Recommended method for installing nodejs with package manager on Debian (minus sudo)
RUN apt-get update \
    && apt-get install -y \
    graphviz \
    libcairo2 \
    libcairo2-dev \
    libgraphviz-dev \
    libjpeg-dev \
    libxml2-dev \
    libxslt1-dev \
    libzmq3-dev

COPY requirements.txt /srv/openta/django/requirements.txt
WORKDIR /srv/openta/django
RUN pip install -r requirements.txt
RUN pip install gunicorn==19.9.0
RUN pip uninstall --yes psycopg2
RUN pip install psycopg2-binary==2.7.7
RUN apt-get update
RUN apt-get install --yes --no-install-recommends ca-certificates curl gpg 
RUN echo "deb http://packages.cloud.google.com/apt gcsfuse-stretch main" | tee /etc/apt/sources.list.d/gcsfuse.list 
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - 
RUN apt-get update 
RUN apt-get install --yes gcsfuse 
RUN mkdir -p /srv/multicourse
#COPY . /srv/openta
#EXPOSE 8000
