upstream openta {
    server web:8000;
}

server {
    listen              443 ssl;
    server_name         opentaproject.com;
    ssl_certificate     /etc/letsencrypt/live/opentaproject.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/opentaproject.com/privkey.pem;

    location /openta/static {
        alias /srv/openta/django/backend/deploystatic;
    }

    location /openta/exerciseasset/ {
        internal;
        alias /srv/openta/exercises/;
        expires 10d;
    }

    location /openta/answerimages/ {
        internal;
        alias /srv/openta/django/backend/media/answerimages/;
    }
    location /openta/media/public/ {
        alias /srv/openta/django/backend/media/public/;
    }
    location /openta/media/CACHE/ {
        internal;
        alias /srv/openta/django/backend/media/CACHE/;
        expires 10d;
    }
 


    location / {
        proxy_pass http://openta;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }


     #location /openta {
     #       proxy_set_header        Host            $host;
     #       proxy_set_header        X-Real-IP       $remote_addr;
     #       proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
     #       proxy_pass_header       Set-Cookie;
     #   }


    #return 200 'Let\'s Encrypt certificate was successfully installed!';
    #add_header Content-Type text/plain;
}
