# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 24, 9, 51, 46, 537761, tzinfo=utc)),
        ),
    ]
