# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0025_exercisemeta_exercise_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'permissions': (('reload', 'Can reload exercises from disk'),)},
        ),
    ]
