# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0027_auto_20160915_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'permissions': (('reload', 'Can reload exercises from disk'), ('edit', 'Can edit exercises in frontend'), ('create', 'Can create exercises in frontend'))},
        ),
    ]
