# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0029_auto_20160915_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'permissions': (('reload_exercise', 'Can reload exercises from disk'), ('edit_exercise', 'Can edit exercises in frontend'), ('create_exercise', 'Can create exercises in frontend'), ('administer_exercise', 'Can administer exercise options'))},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('log_question', 'Answers are logged'),)},
        ),
    ]
