# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0035_auto_20161013_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanswer',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageanswer', to='exercises.Exercise'),
        ),
    ]
