# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0037_exercisemeta_sort_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemeta',
            name='sort_key',
            field=models.CharField(default='', max_length=255, verbose_name='Sort order key'),
        ),
    ]
