# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0040_auto_20161019_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_agent',
            field=models.TextField(default=''),
        ),
    ]
