# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0047_auto_20161209_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditexercise',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
