# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0051_auditexercise_force_passed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auditexercise',
            unique_together=set([('student', 'exercise')]),
        ),
    ]
