# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0059_auto_20170315_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditexercise',
            old_name='closed',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='auditexercise',
            name='done',
        ),
        migrations.AddField(
            model_name='auditexercise',
            name='revision_needed',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='auditexercise',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
