# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0062_auto_20170412_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexercise',
            name='exercise_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
