# Generated by Django 2.0.4 on 2018-12-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0070_exercisemeta_student_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexercise',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
