# Generated by Django 2.0.4 on 2019-07-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0073_auto_20190708_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemeta',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Recommended', 'Recommended'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default=None, max_length=64, null=True),
        ),
    ]
