# Generated by Django 2.2 on 2020-11-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0075_auto_20201107_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnsswerManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
