# Generated by Django 2.0.4 on 2020-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0083_auto_20200610_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemeta',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
