# Generated by Django 2.2 on 2021-01-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0086_auto_20210115_2212'),
        ('exercises', '0076_imageansswermanager'),
    ]

    operations = [
    ]
