#!/usr/bin/env bash
echo "DOING PRE-COMMIT"
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
gh=`git log -n 1 | head -n 1 | sed -e "s/^commit //" | head -c 8`

# exit if there are no staged files
[ -z "$FILES" ] && exit 0

# for each staged file
for FILE in $FILES; do
    echo "DO ${FILE}"
    pwd
    if [[ "$FILE" =~ \.py?$ ]]; then
        # ensure there are no ESLint errors
        django/env/bin/autoflake -c   --remove-all-unused-imports $FILE
        if [[ "$?" != 0 ]]; then
            echo "autoflake is reporing a problem with $FILE "
            exit 1
        fi
    	django/env/bin/autoflake  --in-place --remove-all-unused-imports $FILE
    	django/env/bin/black $FILE
    fi
    # Add back the file to staging
    git add $FILE
done
#ls 
#echo now touch  static-${gh}
#touch static-${gh}


exit 0
