[uwsgi]
logger = syslog:%n

chdir           = /srv/%n/django/backend
module          = backend.wsgi
home            = /srv/%n/django/env/
plugins = python3, logfile, syslog

master          = true
processes       = 10
socket          = /srv/%n/django/backend/%n.sock
chmod-socket    = 666
uid = www-data
gid = www-data
vacuum          = true
max-requests	= 50
