"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys
import backend.version as version

RUNNING_DEVSERVER = len(sys.argv) > 1 and sys.argv[1] == 'runserver'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# If the installation is available at a suburl this should be set to the url
# path. (Also needs to be set in frontend/app/settings.js (see
# settings_example.js) Example: If the site is available at
# http://domain.com/subpath/ this variable should be set to (note trailing
# slash) SUBPATH = 'subpath/'
SUBPATH = ''
VERSION = version.get_version_string()

SECRET_KEY = 'this_should_be_set_to_a_generated_key!'
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_URL = '/' + SUBPATH + 'login/'
LOGIN_REDIRECT_URL = '/' + SUBPATH

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'exercises.apps.ExercisesConfig',
    'course.apps.CourseConfig',
    'users.apps.UsersConfig',
    'workqueue.apps.WorkqueueConfig',
    'widget_tweaks',
    'django_extensions',
    'imagekit',
    'django_rq',
    'hijack',
    'compat',
    'import_export',
]

MIDDLEWARE = [
    'backend.middleware.SameSiteMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ]
        },
    }
]

WSGI_APPLICATION = 'backend.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/' + SUBPATH + 'static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
STATIC_ROOT = os.path.join(BASE_DIR, "deploystatic")
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

MEDIA_TAG = 'media'
MEDIA_URL = MEDIA_TAG + '/'
MEDIA_ROOT = os.path.join(BASE_DIR, MEDIA_TAG)

FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.TemporaryFileUploadHandler']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.SessionAuthentication',),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'middle': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(filename)s %(funcName)s [%(message)s]'
        },
        'simple': {'format': '%(levelname)s %(message)s'},
    },
    'handlers': {
        'stderr': {'level': 'DEBUG', 'class': 'logging.StreamHandler', 'formatter': 'middle'},
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'backupCount': 4,
            'maxBytes': 5242880,
            'filename': 'logfile',
            'formatter': 'middle',
        },
    },
    'root': {'handlers': ['file', 'stderr'], 'level': 'DEBUG'},
    'loggers': {'django': {'handlers': ['file', 'stderr'], 'level': 'ERROR', 'propagate': True}},
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/tmp/django_cache',
    }
}

# Enable the user hijack app for get requests for it to integrate with the frontend.
HIJACK_ALLOW_GET_REQUESTS = True
HIJACK_AUTHORIZE_STAFF = True

# Default to handling queue tasks in main thread
RQ_QUEUES = {
    'default': {
        'HOST': 'localhost',
        'DB': 0,
        'PORT': 6379,
        'ASYNC': False,
        'DEFAULT_TIMEOUT': 20 * 60,
    }
}
