# Generated by Django 2.0.4 on 2019-10-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190428_1139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opentauser',
            unique_together=set(),
        ),
    ]
