# Generated by Django 2.0.4 on 2020-07-13 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workqueue', '0007_auto_20190516_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegradeTask',
            fields=[
                ('queuetask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workqueue.QueueTask')),
                ('exercise', models.CharField(default=None, max_length=64)),
            ],
            bases=('workqueue.queuetask',),
        ),
    ]
