# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2021-05-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashkey', models.CharField(blank=True, default='', max_length=64)),
                ('language', models.CharField(blank=True, default='', max_length=8)),
                ('translated_text', models.CharField(blank=True, default='', max_length=1024)),
                ('original_text', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
