# Generated by Django 3.1.5 on 2021-05-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='altkey',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
