# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2021-06-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_translation_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='original_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translated_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
