#!/bin/bash
echo "Setting docker token in cluster..."
kubectl create secret generic dockerkey --from-file=.dockerconfigjson=$HOME/.docker/config.json --type=kubernetes.io/dockerconfigjson
echo "Done."
