apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - gunicorn
        - backend.wsgi:application
        - --bind
        - 0.0.0.0:8000
        - --env
        - DJANGO_SETTINGS_MODULE=backend.settings_production_docker
        env:
        - name: WEB_CONCURRENCY
          value: "10"
        image: web-image:1
        imagePullPolicy: Never
        name: web
        resources: {}
        volumeMounts:
        - mountPath: /srv/openta/django/backend/media
          name: media
        workingDir: /srv/openta/django/backend/
      restartPolicy: Always
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
status: {}
