# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-04-28 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentauser',
            name='immutable_user_id',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opentauser',
            name='lis_person_contact_email_primary',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opentauser',
            name='lis_person_name_family',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opentauser',
            name='lis_person_name_full',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opentauser',
            name='lis_person_name_given',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opentauser',
            name='lti_context_id',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opentauser',
            name='lti_roles',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opentauser',
            name='lti_tool_consumer_instance_guid',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='opentauser',
            name='lti_user_id',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='opentauser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opentauser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='opentauser',
            unique_together={('lti_user_id', 'lti_context_id', 'lti_tool_consumer_instance_guid')},
        ),
    ]
