apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openta-ingress
spec:
  rules:
  - http:
      paths:
      # Corresponding to first running ./addsubpath example_subpath1 ...
      # and then deploying with kubectl apply -f example_subpath1/
      - path: /example_subpath1/*
        backend:
          serviceName: example_subpath1
          servicePort: 80
      - path: /example_subpath2/*
        backend:
          serviceName: example_subpath2
          servicePort: 80