apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ${SUBPATH}-data
  name: ${SUBPATH}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5000Mi
status: {}
