# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20160819_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='number',
            new_name='question_id',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('question_id', 'exercise_name')]),
        ),
    ]
