# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20160819_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='exercise_name',
            new_name='exercise',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('question_id', 'exercise')]),
        ),
    ]
