# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('exercises', '0007_auto_20160824_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_name',
            new_name='exercise_key',
        ),
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
