# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_id',
            new_name='question_key',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('question_key', 'exercise')]),
        ),
    ]
