# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_auto_20160830_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='exercise_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
