# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_imageanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanswer',
            name='image',
            field=models.ImageField(upload_to=exercises.models.answer_image_filename),
        ),
    ]
