# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 10:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_imageanswer_exercise_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_date', models.DateTimeField(null=True)),
                ('pdf_solution', models.BooleanField(default=False)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('required', models.BooleanField(default=False)),
                ('bonus', models.BooleanField(default=False)),
                ('server_reply_time', models.DurationField(default=datetime.timedelta(0))),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise')),
            ],
        ),
    ]
