# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0020_auto_20160913_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemeta',
            name='deadline_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='server_reply_time',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
