# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0023_exercisemeta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemeta',
            name='exercise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='exercises.Exercise'),
        ),
    ]
