# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0024_auto_20160914_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemeta',
            name='exercise_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
