# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0026_auto_20160915_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'permissions': (('reload', 'Can reload exercises from disk'), ('edit', 'Can edit exercises'), ('create', 'Can edit exercises'))},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('log', 'Answers are logged'),)},
        ),
    ]
