# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0030_auto_20160915_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemeta',
            name='deadline_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='deadline_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
