# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0032_remove_exercisemeta_deadline_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemeta',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
