# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0033_exercisemeta_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisemeta',
            old_name='pdf_solution',
            new_name='solution',
        ),
    ]
