# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0036_auto_20161014_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemeta',
            name='sort_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
