# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0038_auto_20161018_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemeta',
            name='image',
            field=models.BooleanField(default=False, verbose_name='Image upload'),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='solution',
            field=models.BooleanField(default=False, verbose_name='Show solution'),
        ),
    ]
