# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0039_auto_20161019_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemeta',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Obligatory'),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='solution',
            field=models.BooleanField(default=False, verbose_name='Publish solution'),
        ),
    ]
