# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0044_auto_20161108_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'permissions': (('reload_exercise', 'Can reload exercises from disk'), ('edit_exercise', 'Can edit exercises in frontend'), ('create_exercise', 'Can create exercises in frontend'), ('administer_exercise', 'Can administer exercise options'), ('view_solution', 'Can view exercise solution (even if not published)'), ('view_statistics', 'Can view student progress statistics'), ('view_student_id', 'Can view student identity'))},
        ),
    ]
