# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0046_auditexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditexercise',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
