# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0048_auto_20161209_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexercise',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
