# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0049_auditexercise_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexercise',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
