# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0050_auditexercise_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexercise',
            name='force_passed',
            field=models.BooleanField(default=False),
        ),
    ]
