# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0053_auto_20170209_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditexercise',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
