# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0054_auto_20170214_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexercise',
            name='fileresponse',
            field=models.FileField(blank=True, default=None, null=True, upload_to=exercises.models.audit_fileresponse_filename),
        ),
        migrations.AddField(
            model_name='imageanswer',
            name='filetype',
            field=models.CharField(choices=[('IMG', 'Image'), ('PDF', 'Pdf')], default='IMG', max_length=3),
        ),
        migrations.AddField(
            model_name='imageanswer',
            name='pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to=exercises.models.answer_image_filename),
        ),
        migrations.AlterField(
            model_name='imageanswer',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=exercises.models.answer_image_filename),
        ),
    ]
