# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0055_auto_20170306_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemeta',
            name='allow_pdf',
            field=models.BooleanField(default=False, verbose_name='Allow pdf as image upload'),
        ),
    ]
