# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0056_exercisemeta_allow_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditResponseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('filetype', models.CharField(choices=[('IMG', 'Image'), ('PDF', 'Pdf')], default='IMG', max_length=3)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=exercises.models.audit_response_filename)),
                ('pdf', models.FileField(blank=True, default=None, null=True, upload_to=exercises.models.audit_response_filename)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsefiles', to='exercises.AuditExercise')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
