# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0057_auditresponsefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditexercise',
            name='fileresponse',
        ),
    ]
