# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0058_remove_auditexercise_fileresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditexercise',
            old_name='resolved',
            new_name='closed',
        ),
        migrations.AddField(
            model_name='auditexercise',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
