# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0060_auto_20170315_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexercise',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
