# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0061_auditexercise_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditexercise',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='exercises.Exercise'),
        ),
    ]
