# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0063_auditexercise_exercise_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='translated_name',
            field=models.CharField(default='{}', max_length=512),
        ),
    ]
