# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0064_exercise_translated_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemeta',
            name='feedback',
            field=models.BooleanField(default=True, verbose_name='Feedback to student'),
        ),
    ]
