# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2018-08-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0069_exercise_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemeta',
            name='student_assets',
            field=models.BooleanField(default=False, verbose_name='Student assets'),
        ),
    ]
