# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2018-08-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0071_auditexercise_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='exercise_key',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question_key',
        ),
        migrations.RemoveField(
            model_name='auditexercise',
            name='exercise_key',
        ),
        migrations.RemoveField(
            model_name='exercisemeta',
            name='exercise_key',
        ),
        migrations.RemoveField(
            model_name='imageanswer',
            name='exercise_key',
        ),
    ]
