# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-10-15 16:09

from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0072_auto_20180824_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditresponsefile',
            name='pdf',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, upload_to=exercises.models.audit_response_filename),
        ),
        migrations.AlterField(
            model_name='imageanswer',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=512, null=True, upload_to=exercises.models.answer_image_filename),
        ),
        migrations.AlterField(
            model_name='imageanswer',
            name='pdf',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, upload_to=exercises.models.answer_image_filename),
        ),
    ]
