# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-07-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0072_auto_20180824_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemeta',
            name='difficulty',
            field=models.CharField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=None, max_length=64, null=True),
        ),
    ]
