# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.2 on 2020-11-05 23:34

import django.core.files.storage
from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0073_auto_20191015_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageanswer',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media', location='/srv'), upload_to=exercises.models.answer_image_filename),
        ),
        migrations.AlterField(
            model_name='imageanswer',
            name='pdf',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media', location='/srv'), upload_to=exercises.models.answer_image_filename),
        ),
    ]
