# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-07-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0074_auto_20190708_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemeta',
            name='difficulty',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
