# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-11-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0075_bincounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bincounts',
            name='interval',
        ),
    ]
