# Generated by Django 2.0.4 on 2019-11-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0073_auto_20191015_1809'),
        ('exercises', '0075_auto_20190708_1332'),
    ]

    operations = [
    ]
