# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-11-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0076_remove_bincounts_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregation',
            name='image_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
