# Generated by Django 2.0.4 on 2019-11-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0077_aggregation_image_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregation',
            name='audit_needs_attention',
            field=models.BooleanField(default=False),
        ),
    ]
