# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-11-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0078_aggregation_audit_needs_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregation',
            name='image_exists',
            field=models.BooleanField(default=False),
        ),
    ]
