# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-11-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0079_aggregation_image_exists'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aggregation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aggregation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='aggregation',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='aggregation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bincounts',
            name='course',
        ),
        migrations.RemoveField(
            model_name='bincounts',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='aggregation',
        ),
        migrations.DeleteModel(
            name='Aggregation',
        ),
        migrations.DeleteModel(
            name='Bincounts',
        ),
    ]
