# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-03-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0076_merge_20191103_1239'),
        ('exercises', '0080_auto_20191118_2113'),
    ]

    operations = [
    ]
