# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0081_merge_20200306_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditexercise',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
