# Generated by Django 2.0.4 on 2020-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0082_auditexercise_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditexercise',
            name='points',
            field=models.TextField(blank=True, default=''),
        ),
    ]
