# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.2 on 2020-10-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0084_exercisemeta_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='exerciseseed',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answer',
            name='questionseed',
            field=models.TextField(default=''),
        ),
    ]
