# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.2 on 2021-01-15 21:12

import django.core.files.storage
from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0085_auto_20201013_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditresponsefile',
            name='pdf',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/srv/multicourse'), upload_to=exercises.models.audit_response_filename),
        ),
        migrations.AlterField(
            model_name='imageanswer',
            name='pdf',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/srv/multicourse'), upload_to=exercises.models.answer_image_filename),
        ),
    ]
