# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.2 on 2021-01-23 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0087_merge_20210115_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageAnsswerManager',
            new_name='ImageAnswerManager',
        ),
    ]
