# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2021-01-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0088_auto_20210124_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditexercise',
            name='revision_needed',
            field=models.BooleanField(null=True),
        ),
    ]
