# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2021-02-22 01:48

import django.core.files.storage
from django.db import migrations, models
import exercises.models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0089_auto_20210124_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditresponsefile',
            name='pdf',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/subdomain-data'), upload_to=exercises.models.audit_response_filename),
        ),
        migrations.AlterField(
            model_name='imageanswer',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/subdomain-data'), upload_to=exercises.models.answer_image_filename),
        ),
        migrations.AlterField(
            model_name='imageanswer',
            name='pdf',
            field=models.FileField(blank=True, default=None, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/subdomain-data'), upload_to=exercises.models.answer_image_filename),
        ),
    ]
