# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2022-07-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0090_auto_20210222_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemeta',
            name='allow_pdf',
            field=models.BooleanField(default=False, help_text='Select to not automatically convert pdf to png.', verbose_name='Do not convert pdf to png.'),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='bonus',
            field=models.BooleanField(default=False, help_text='Flag exercise as bonus.'),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='difficulty',
            field=models.CharField(blank=True, default=None, help_text='Optional tag for the exercise that can be edited in course options.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='feedback',
            field=models.BooleanField(default=True, help_text='Unselect to choose "Exam mode" i.e.  students will not find out if the answer is right or wrong', verbose_name='Feedback to student'),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='image',
            field=models.BooleanField(default=False, help_text='Select to allow student upload of pdf or png. pdf will be converted to png unless overridden. ', verbose_name='Require student upload of image or pdf'),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='locked',
            field=models.BooleanField(default=False, help_text='Select to lock the question so student can no longer submit answers or images.  '),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='required',
            field=models.BooleanField(default=False, help_text='Flag exercise as obligatory', verbose_name='Obligatory'),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='solution',
            field=models.BooleanField(default=False, help_text='Select to allow students to see the solutions listed in the solution tag.', verbose_name='Publish solution'),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='sort_key',
            field=models.CharField(default='', help_text='An invisible field to order the exercises in a folder.', max_length=255, verbose_name='Sort order key.'),
        ),
        migrations.AlterField(
            model_name='exercisemeta',
            name='student_assets',
            field=models.BooleanField(default=False, help_text='Select to allow student to upload arbitrary files into asset directory.', verbose_name='Enable student assets'),
        ),
    ]
