# Generated by Django 5.2.6 on 2025-10-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0091_auto_20220702_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemeta',
            name='allow_ai',
            field=models.BooleanField(default=False),
        ),
    ]
