# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 5.2.6 on 2025-10-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0092_exercisemeta_allow_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemeta',
            name='allow_ai',
            field=models.BooleanField(default=False, help_text='Select to allow students to make openai queries', verbose_name='Allow openai queries'),
        ),
    ]
