apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: v212b-data
  name: v212b-data
  namespace: openta-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5000Mi
status: {}
