apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: v300-data
  name: v300-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5000Mi
status: {}
