#!/bin/bash
kubectl exec $(kubectl get pod -l name=$1 -o jsonpath="{.items[0].metadata.name}") -c web ./manage.py migrate
kubectl exec $(kubectl get pod -l name=$1 -o jsonpath="{.items[0].metadata.name}") -c web ./manage.py loaddata fixtures/auth.json
kubectl exec $(kubectl get pod -l name=$1 -o jsonpath="{.items[0].metadata.name}") -c web ./manage.py loaddata fixtures/course.json
