# Generated by Django 2.0.4 on 2019-11-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='ready_for_audit',
            field=models.BooleanField(default=False),
        ),
    ]
