# Generated by Django 2.0.4 on 2019-11-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0006_answers_complete_by_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='correct_by_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='image_by_deadline',
            field=models.BooleanField(default=False),
        ),
    ]
