# Generated by Django 2.0.4 on 2019-12-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0008_answers_questionlist_is_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='audit_published',
            field=models.BooleanField(default=False),
        ),
    ]
