# Generated by Django 2.0.4 on 2020-01-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0011_auto_20200103_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='force_failed',
            field=models.BooleanField(default=False),
        ),
    ]
