apiVersion: v1
kind: Service
metadata:
  name: wildcard-demo
  namespace: opentaproject-com
spec:
  type: ClusterIP
  selector:
    app: wildcard-demo
  ports:
    - port: 80
      targetPort: gunicorn
      name: http
