# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20160921_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registration_password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Registreringslösenord'),
        ),
    ]
