# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_course_long_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deadline_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
