# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registration_domains',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
