# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_registration_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registration_by_domain',
            field=models.BooleanField(default=False),
        ),
    ]
