# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20171207_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='email_host',
            field=models.CharField(blank=True, default='localhost', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='email_host_password',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='email_host_user',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='email_reply_to',
            field=models.CharField(blank=True, default='localhost', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='motd',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
