# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2018-10-17 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='email_reply_to',
            field=models.CharField(blank=True, default='', max_length=255, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
