# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2018-12-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20181123_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='use_auto_translation',
            field=models.BooleanField(default=False),
        ),
    ]
