# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2018-11-15 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_course_use_auto_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
