# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2018-11-15 15:07

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Course = apps.get_model('course', 'Course')
    for row in Course.objects.all():
        row.course_key = uuid.uuid4()
        row.save(update_fields=['course_key'])

class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_course_course_key'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
