# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-07-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20190428_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='google_auth_string',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='course',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
