# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-10-27 20:30

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Course = apps.get_model('course', 'Course')
    for row in Course.objects.all():
        row.lti_key = uuid.uuid4()
        row.lti_secret = uuid.uuid4()
        row.save(update_fields=['lti_key', 'lti_secret'])

class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20190428_1139'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
