# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20190428_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='use_email',
            field=models.BooleanField(default=False),
        ),
    ]
