# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2019-07-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('course', '0025_course_email_from_user'), ('course', '0026_auto_20190716_0007'), ('course', '0027_auto_20190716_0015')]

    dependencies = [
        ('course', '0024_course_use_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='email_username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
