# Generated by Django 2.0.4 on 2019-07-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20190715_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='languages',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
