# Generated by Django 2.0.4 on 2019-10-27 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20191027_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lti_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lti_secret',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
