# Generated by Django 2.0.4 on 2019-07-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_course_difficulties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulties',
            field=models.CharField(blank=True, default='+:Recommended,Easy:Easy,Med:Medium,Hard:Hard', max_length=512, null=True),
        ),
    ]
