# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-02-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_merge_20191103_1313'),
        ('course', '0028_merge_20191103_1244'),
    ]

    operations = [
    ]
