# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-02-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_merge_20191103_1256'),
        ('course', '0029_merge_20200201_2310'),
    ]

    operations = [
    ]
