# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.0.4 on 2020-02-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_merge_20200202_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='use_lti',
            field=models.BooleanField(default=False),
        ),
    ]
