# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.2 on 2020-10-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_auto_20200821_1245'),
        ('course', '0032_auto_20200821_2341'),
    ]

    operations = [
    ]
