# Generated by Django 2.2 on 2020-12-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_merge_20201029_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gu.se', max_length=255, null=True),
        ),
    ]
