# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 2.2 on 2020-12-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_auto_20201216_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='email_host',
            field=models.CharField(blank=True, default='localhost', max_length=255, null=True),
        ),
    ]
