# Generated by Django 3.1.5 on 2021-03-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_opentasite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenTASite',
        ),
        migrations.AddField(
            model_name='course',
            name='opentasite',
            field=models.CharField(default='', max_length=255),
        ),
    ]
