# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2021-05-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0038_auto_20210301_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.mailgun.org', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='email_host_user',
            field=models.CharField(blank=True, default='postmaster@opentaproject.org', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='email_username',
            field=models.CharField(blank=True, default='postmaster@opentaproject.org', max_length=255, null=True),
        ),
    ]
