# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2021-06-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_auto_20210527_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
