# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2021-06-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0040_course_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_anonymous_student',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
