# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2021-06-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0041_course_allow_anonymous_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='email_host_password',
            field=models.CharField(blank=True, default='wfuhkqyieqaazjsc', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='email_host_user',
            field=models.CharField(blank=True, default='stellan@opentaproject.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='email_username',
            field=models.CharField(blank=True, default='stellan@opentaproject.com', max_length=255, null=True),
        ),
    ]
