# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2018-2025 Stellan Östlund and Hampus Linander

# Generated by Django 3.1.5 on 2022-08-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0043_auto_20210606_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
