# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registration_password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
