# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20160927_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_long_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
