# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20180119_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
