# Generated by Django 2.0.4 on 2018-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_course_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
