# Generated by Django 2.0.4 on 2018-11-23 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20181017_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='owners',
            field=models.ManyToManyField(limit_choices_to={'is_staff': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
