# Generated by Django 2.0.4 on 2019-04-28 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lti_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='lti_secret',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
