# Generated by Django 2.0.4 on 2019-07-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20190707_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulties',
            field=models.CharField(blank=True, default='Recommended,Easy,Medium,Hard', max_length=512, null=True),
        ),
    ]
