# Generated by Django 2.0.4 on 2019-07-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_auto_20190708_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulties',
            field=models.CharField(blank=True, default='+:Recommended,*:Easy,**:Medium,***:Hard', max_length=512, null=True),
        ),
    ]
