# Generated by Django 2.0.4 on 2019-11-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_auto_20190708_1311'),
    ]

    operations = [
    ]
