# Generated by Django 2.0.4 on 2020-02-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_merge_20191103_1313'),
        ('course', '0028_merge_20191103_1244'),
    ]

    operations = [
    ]
