# Generated by Django 2.0.4 on 2019-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_merge_20190901_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='email_username',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='use_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='use_lti',
            field=models.BooleanField(default=False),
        ),
    ]
