# Generated by Django 2.0.4 on 2020-02-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_merge_20200201_2310'),
        ('course', '0026_merge_20191103_1256'),
    ]

    operations = [
    ]
