# Generated by Django 2.0.4 on 2020-02-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_merge_20200202_0021'),
        ('course', '0030_merge_20200201_2334'),
    ]

    operations = [
    ]
