# Generated by Django 2.2 on 2020-08-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_course_use_lti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registration_by_domain',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_by_password',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='use_email',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='use_lti',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
