# Generated by Django 2.2 on 2021-01-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_auto_20201216_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gu.se', max_length=255, null=True),
        ),
    ]
