# Generated by Django 3.1.5 on 2021-01-30 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_opentasite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opentasite',
            old_name='name',
            new_name='subdomain',
        ),
        migrations.AddField(
            model_name='opentasite',
            name='db_name',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
