# Generated by Django 3.1.5 on 2021-01-30 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0038_auto_20210130_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subdomain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.opentasite'),
        ),
    ]
