# Generated by Django 3.1.5 on 2021-02-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_course_subdomain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subdomain',
        ),
        migrations.DeleteModel(
            name='OpenTASite',
        ),
    ]
