# Generated by Django 3.1.5 on 2021-01-30 15:05

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_course_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subdomain',
            field=models.ForeignKey(default=course.models.getfirstOpenTASite, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.opentasite'),
        ),
    ]
