# Generated by Django 3.1.5 on 2021-02-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opentasites', '0003_auto_20210205_2035'),
        ('course', '0040_auto_20210201_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='opentasite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='opentasites.opentasite'),
        ),
    ]
