'joule' : (kg * meter**2)/second**2,
'Newton' : (kg * meter)/second**2, 
'coulomb' : ampere * second, 
'volt' : (kg * meter**2)/(ampere * second**3),
'ohm' : (kg * meter**2)/(ampere**2 * second**3),
'watt' : (kg * meter**2)/second**3, 
'farad' : (ampere * couloumb * second**3)/(kg * meter**2),
'chie' : 1, 
'siemens' : (ampere**2 * second**3)/(kg * meter**2),
'tesla' : kg/(ampere * second**2),
'weber' : (kg * meter**2)/(ampere * second**2),
'henry' : (kg * meter**2)/(ampere**2 * second**2),
'mu_zero' : (kg * meter * Pi)/(2500000 * ampere**2 * second**2),
'speed_of_light' : (2.99792458 * 10**(8) * meter)/second, 
'mu_units' : (kg * meter)/( ampere**2 * second**2),
'mu_zero' :  Pi/2500000 mu_units,
'mu_units' : (kg * meter)/( ampere**2 * second**2),
'epsilon_units' : ( ampere**2 * second**4)/(kg * meter**3),
'epsilon_zero' : (8.85418781762039 * 10**(-12) epsilon_units
